### ISSUE TITLE
Broken on release v22.09-d47b8c8 (or earlier)

### ISSUE THREAD

**Issue by Organizer21** [wltb/ff_feedcleaner#10]
My TT was so old that the current FF_FC version failed to work properly, so I finally updated TT on one machine to the very latest and now it seems feedcleaner is crashing the installation fully and causing TT to go into safe mode. Any chance for an quick update? I presume it is linked to the plugin as it stand but I can be wrong. What I am seing beyond some an 500 Error onm the plugin page is the following in logs:

```
E_COMPILE_ERROR (64) | plugins.local/ff_feedcleaner/init.php:103
Declaration of ff_FeedCleaner::hook_feed_parsed($rss) must be compatible with Plugin::hook_feed_parsed($parser, $feed_id)

---------------------------

E_USER_WARNING (512) | classes/pluginhost.php:461
Plugin ff_feedcleaner has caused a PHP fatal error so it won't be loaded again in this session.
1. classes/pluginhost.php(461): user_error(Plugin ff_feedcleaner has caused a PHP fatal error so it won't be loaded again in this session.)
2. classes/pluginhost.php(427): load(af_comics,af_psql_trgm,af_readability,af_redditimgur,af_unburn,af_youtube_embed,af_zz_vidmute,auth_internal,auth_remote,auto_assign_labels,bookmarklets,cache_starred_images,data_migration,ff_feedcleaner,hotkeys_force_top,hotkeys_noscroll,hotkeys_swap_jk,ng...)
3. classes/pref/prefs.php(803): load_all()
4. backend.php(136): getPluginsList()
```

**Comment by wltb** [comment]
IIRC, in one of the latest big rewrites fox added the plugin hook functions to the base class, or something like that, to allow for more thorough static analyzing; and that is what this error is about.

This is easily fixable, I'll have a look at it in the next few days. Other than that, I don't recall breaking changes in the core, but if you should find any related to this plugin, I'll try to investigate.

**Comment by Organizer21** [comment]
That's awesome and makes me happy - I do hope it's an easy and quick one. I tried to look at a few other plugins to see if there would be something I could learn as to reolve it, but I gave up. My coding skills this area is more than lacking unfortunately.

**Comment by wltb** [comment]
Sorry that this took so long, I had github trouble. I changed the signature of the hook functions and put the commit into the [adapting branch](/wltb/ff_feedcleaner/tree/adapting). Let me know if this fixes it, or if there is anything else that is broken.

**Comment by Organizer21** [comment]
No worries, I've been out for some days. I'll be downloading that now and giving it a go.

**Comment by Organizer21** [comment]
Enabling the plugin now works, but any attempt to add rules seems to fail...

`Uncaught ReferenceError: fffc_comm is not defined`

`ReferenceError: fffc_comm is not defined
    at Object.eval [as onSubmit] (eval at _functionFromScript (https://192,168,1.20:8200/tt-rss/lib/dojo/tt-rss-layer.js?1662183355:8:5182), <anonymous>:5:3)
    at Object._onSubmit (https://192,168,1.20:8200/tt-rss/lib/dojo/tt-rss-layer.js?1662183355:8:280563)
    at HTMLFormElement.<anonymous> (https://192,168,1.20:8200/tt-rss/lib/dojo/dojo.js?1662183355:8:33691)
    at Object.__onClick (https://192,168,1.20:8200/tt-rss/lib/dojo/tt-rss-layer.js?1662183355:8:216322)
    at HTMLSpanElement.<anonymous> (https://192,168,1.20:8200/tt-rss/lib/dojo/dojo.js?1662183355:8:33691)`

**Comment by wltb** [comment]
I'm so sorry that you are my alpha tester, I'll look into it, but it also means that the backend stuff seems to be working fine since that is a JavaScript error. If you want to, you can cherry pick the latest commit in the adapting branch and apply it the commit before the JS refactoring until I figure things out.

**Comment by Organizer21** [comment]
No worries at all he-he, I am just very, very, happy that you maintain this plugin as it's become a necessity :)  As my temporary fix on for new clean installation, I copied the FC plugin data row from my previous TT installation (luckily I don’t change rules every day, but ofc. it would be a massive hassle to update this way). I'll hold out for your update and I’m hope the fix wont’ cause you too much of an headache 😊

**Comment by Organizer21** [comment]
Just a side note; if I go to the "System" tab, click the severity dropdown and set to ERROR I get an error while clicking any further on the page, including on the "Mail Configuration" and "PHP Information" tabs. I think mayby related to the issue!? I will try again once you've resolved the current plugin JS issue.

`Uncaught TypeError: Cannot read properties of undefined (reading '_wrapperWidget')`
`TypeError: Cannot read properties of undefined (reading '_wrapperWidget')
    at Object._transition (https://nas.synology.me:8243/tt-rss/lib/dojo/tt-rss-layer.js?1662183355:8:338011)
    at Object.selectChild (https://nas.synology.me:8243/tt-rss/lib/dojo/tt-rss-layer.js?1662183355:8:342010)
    at Object._onTitleClick (https://nas.synology.me:8243/tt-rss/lib/dojo/tt-rss-layer.js?1662183355:8:332490)
    at HTMLDivElement.<anonymous> (https://nas.synology.me:8243/tt-rss/lib/dojo/dojo.js?1662183355:8:33691)`

**Comment by Organizer21** [comment]
Hey buddy, how is the progress? I've been busy the last 12 days, so only just checked back here today as to look for the update.

**Comment by wltb** [comment]
You're guessing right, for a while, I wasn't in a position to help anybody with anything. But I had given your problem some thought in October, and I need your help fixing it since it works fine on my installation.

First step is that we need to check if it's a server-side or a client problem. Could you check if the content of the _BackendComm.js_ file is included? To do that, you simply could open the source of ttRSSes Preferences section and search for **BackendComm**. When it's there, we know that it's no PHP problem.

After that, the second step would be to tell me what browser you are using so I could reproduce this, or at least use google-fu. It could very well be that the JS code that tries to avoid redefining a class is not portable.

**Comment by hjalmarlucius** [comment]
I have this same issue with the same error message. Just started using ttRSS from docker - everything on latest versions.

**Comment by kaistian** [comment]
@wltb I have the same problem, after applying the commit in the adapting branch I was able to enable the plugin.
But when saving the rules I do get `Uncaught ReferenceError: fffc_comm is not defined` as Organizer21.

> First step is that we need to check if it's a server-side or a client problem. Could you check if the content of the _BackendComm.js_ file is included? To do that, you simply could open the source of ttRSSes Preferences section and search for **BackendComm**. When it's there, we know that it's no PHP problem.

In RSS Preference I right clicked an choose View Source, searching for BackendComm i get one hit on line 118
```
<script>
    const fffc_comm = new BackendComm("ff_feedcleaner");
</script>

```

> After that, the second step would be to tell me what browser you are using so I could reproduce this, or at least use google-fu. It could very well be that the JS code that tries to avoid redefining a class is not portable.

Backend:
Apache 2.4.52
PHP 8.1.2

Frontend:
Both has the same problem, and same source code as above.
Firefox 114.0.2
Chromium 103.0.5060.134

**Comment by wltb** [comment]
Seems like this is a really strange problem. It still works fine for me, and I'm now on a fairly recent version of Tiny Tiny RSS.

> In RSS Preference I right clicked an choose View Source, searching for BackendComm i get one hit on line 118
> 
> ```
> <script>
>     const fffc_comm = new BackendComm("ff_feedcleaner");
> </script>
> ```
> 
> > After that, the second step would be to tell me what browser you are using so I could reproduce this, or at least use google-fu. It could very well be that the JS code that tries to avoid redefining a class is not portable.
> 
> Backend: Apache 2.4.52 PHP 8.1.2
> 
> Frontend: Both has the same problem, and same source code as above. Firefox 114.0.2 Chromium 103.0.5060.134

Thank you, that's helpful, just not for debugging the problem at hand. Maybe it works on my instance because other plugins I have activated shadow the error. I'll try to investigate further with a fresh instance when I have some time, and hopefully soon.

**Comment by wltb** [comment]
@kaistian @Organizer21 Could you check the latest commit in the adapting branch? This should fix it. Sorry it took me so long.

**Comment by kaistian** [comment]
No worries, I'm happy you eventually had time to look into it.
The patch is tested and it working great, thank you.

**Comment by wltb** [comment]
All right, I'll update the master branch then.
