### ISSUE TITLE
No preferences dialog visible

### ISSUE THREAD

**Issue by pir187** [wltb/ff_feedcleaner#4]
Hello,

I just cloned the repo into the plugins directory of my TT-RSS installation (V16.3) and activated the plugin for one my users, but nothing happens.

What might go wrong here? Can you give me a hint? Where can I check for errors and/or configure the plugin?

Thx for your help in advance! pir187

**Comment by wltb** [comment]
Hi, sorry was sick and then forgot. But to be honest I think I can't do much for you. Only similar experience I had was when another plugin used the same html id for its tab, only one tab showed up then.
Check ttrss'es log, the webserver's log and the browser's log, maybe you can locate the error.
