### ISSUE TITLE
Preview pane not showing

### ISSUE THREAD

**Issue by Organizer21** [wltb/ff_feedcleaner#5]
Hi there, maybe not the right place, though in case you know before I try tiny forums or similar. I'm running this one TTRSS v16.1 and it seems to work just fine, though under the feedcleaner tab I only see the box with the JSON, a box with enable ext log and auto correction, and a SAVE button. I do not have the preview pane and option to check DIFF? I'm on ubuntu 14.04 and the diff command at least works from console at least as expected, any thoughts, maybe I'm just being blind or stupid?

![image](https://cloud.githubusercontent.com/assets/16366292/16545459/4c38bccc-4123-11e6-9588-ef06e78e71ec.png)

**Comment by wltb** [comment]
GUI stuff is really hard to debug, generally you should check the logs of ttrss, the web server and the browser. But in this case, maybe you don't have to do that: Did you update ff_feedcleaner to the latest version? If you did, the _automatic correction_ option shouldn't be there anymore, and the _show diff_ pane should show up then.

**Comment by Mannshoch** [comment]
Have same error. I'm on the actual release 0.9.

**Comment by Organizer21** [comment]
Older thread but for reference my issue was down to the version, Iater installed cleanly and again and I now have the show_diff panel and everything works as intended. This can be closed from my side at least.
