### ISSUE TITLE
OR (|} in Regex appears not to work

### ISSUE THREAD

**Issue by Davelohan** [wltb/ff_feedcleaner#6]
Hi,

I have described the problem in the TTRSS forum post https://tt-rss.org/forum/viewtopic.php?f=22&t=2123. 

I am trying to take a Google Alert RSS into TTRSS. What comes in has a prefix and postfix. An example is:

https://www.google.com/url?rct=j&sa=t&url=http://thecork.ie/2016/03/16/cork-airport-get-two-new-routes-to-southampton-and-leeds-bradford/&ct=ga&cd=CAIyGzI5ZDZjMWRhMzczNzBlOTU6aWU6ZW46SUU6Ug&usg=AFQjCNGaSw-_EEoppiW7fQFFjFKSbcISEQ

I have done extensive testing over a number of weeks. Eventually I tested the code:

[
{
"URL_re" : "#www\.google\.ie#",  
"type" : "regex",
"pattern": "/http\S+url=|&ct\S+/",
"replacement": ""
}
]

Note: The backslashes are actually double backslash. They appear above, when I save this post, as single backslash.

It appears to work fine for the first part but not for the second: it gets rid of the prefix but not the postfix. The problem appears to lie with the use of the pipe (|) which is legitimate for Regex. Can anything be done to fix?

**Comment by wltb** [comment]
I can't remember what this was about, only that you were advised to write your own plugin IIRC. It seems that you are trying to get the content of the url query parameter, there are indeed more robust solutions available for this in PHP than using regexes.
