### ISSUE TITLE
Still active? Plugin works but has some issues

### ISSUE THREAD

**Issue by Organizer21** [wltb/ff_feedcleaner#7]
While the plugin still work with the latest TT version, there's now some further issues. E.g. updating the JSON no longer provide a visual popup confirming it being valid or not like in the past (likely due to TT changes) and also when using the Show Diff the error (if one) does not pop up either. 

There's now also some error on line 85, suggesting that maybe you want to use "continue 2"; this seems linked to PHP 7.3+ which is slowly becoming more common to use.

Not sure if you are around, but if you are it would be lovely to see an update version (likely then to last many many more years) ;) thanks for creating this though, have used it quite a bit over the years.

**Comment by wltb** [comment]
I'm still around, and you're right, I'm a bit behind on the latest TT changes. I've also wanted to implement logging to the feed debugger (if that's still in TT…) and reimplement encoding correction.

Right now, I've got some other stuff to do, but I hope I will eventually fix this. Thank you for notifying me.

**Comment by Organizer21** [comment]
Hey buddy, wish I could help, but skills are limited. Just checking in again as it's been a good while and still heavily using this great plugin.

**Comment by Organizer21** [comment]
> I'm still around, and you're right, I'm a bit behind on the latest TT changes. I've also wanted to implement logging to the feed debugger (if that's still in TT…) and reimplement encoding correction.
> 
> Right now, I've got some other stuff to do, but I hope I will eventually fix this. Thank you for notifying me.

Just a friendly ping, hope you are all good. Just though to check-in as I was fixing some feed issues and ran into some of the incompatibility issues again. Also if there would be a way for a future update to also hook into the official "readability" plugin, so that it could clean those as well it would be awesome.

**Comment by Organizer21** [comment]
Where could he be :) ref. my comment month ago... now using mercury as well as readability... but the problem seems that both those plugins fetches the full text after the feedcleaner has done its jobs. So having this run after or there being some way to configure it to optionally hook into them would be key to be able to do any feedcleaning at all when the content is fetched (presuming this issue is with the plugin and not something that can't be controlled).

**Comment by wltb** [comment]
All right, I already fixed the missing notification issue (javascript in core was modified) and saw the _diff not working_ issue, but haven't investigated it yet. I'm not sure this is worth keeping since logging to the feed debugger is possible, and the feed debugger can be called from the GUI.

> Where could he be :) ref. my comment month ago... now using mercury as well as readability... but the problem seems that both those plugins fetches the full text after the feedcleaner has done its jobs.

Yeah, the plugin runs in the first two hooks after the feed is fetched, so it only processes the raw XML ATM. I don't know what you are trying to achieve, can you give an example? I could hook into _article_filter_ or _sanitize_, where the content of the articles is processed and can be altered – if I deem this worthwhile.

**Comment by wltb** [comment]
All right, notifications should be fixed now (or were actually already fixed almost a year ago, apologies for my lagging). Regarding the "later cleaning", could you open a new issue if you still need this?
