### ISSUE TITLE
Broken on release  v21.05-b2f888e38

### ISSUE THREAD

**Issue by Bill-Thorsteinson** [wltb/ff_feedcleaner#9]
I pulled the latest tt_rrs release and ff_feedcleaner broke.  I found three issues

- csrf token is neither set nor ignored.  
- prefs tab function no longer takes an argument.
- Ajax is no longer provided by tt_rrs.

I have a minimal patch that allows ff_feedcleaner. Patch uses prototype.js from the tt-rrs js subdirectory. It needs to be added manually.  

[0001-Minimial-fixes-to-work-with-new-tt-rss-releease.patch.txt](https://github.com/wltb/ff_feedcleaner/files/6446875/0001-Minimial-fixes-to-work-with-new-tt-rss-releease.patch.txt)

**Comment by wltb** [comment]
Thank you. I'll try to merge ASAP, but I'd prefer to get rid of prototype. If you have some command of JS and a bit of time on your hands, I would appreciate a rewrite – there are some JS functions in ttrss that encapsulate AJAX stuff, or vanilla JS using Fetch API would be nice as well.

If not, I'll take care of this.

**Comment by wltb** [comment]
Sorry that it took me so long, does it work now with latest master branch?

**Comment by Organizer21** [comment]
This was fixed right? At least I had a look at the ...patch.txt and it seems the current version include those changes. Thought as per seperate post there seems to be a new issue with the later TT versions.

**Comment by wltb** [comment]
OK, thank you!
